### ISSUE TITLE
If you disconnect your wallet in MetaMask, the user state is not updated and still displays your wallet hash.

### ISSUE THREAD

**Issue by JayBud** [Cryptorubic/rubic-app#11]
If you disconnect your wallet through the MetaMask extension, the user state is not updated and still displays your wallet hash. This causes trades to fail, while it still looks like you're connected.

![Screenshot 2021-01-26 at 23 32 09](https://user-images.githubusercontent.com/23051443/105922577-3268d480-603b-11eb-927c-182d56621e67.png)

Solution: 
Listen to event/state changes from MetaMask (disconnections), update the user state and render the "Login by MetaMask" component.

Chrome Version 87.0.4280.141 (Official Build) (x86_64)
macOS Catalina Version 10.15.7

**Comment by siandreev** [comment]
Fixed in v2.0.0
