### ISSUE TITLE
Can't running rubic-app

### ISSUE THREAD

**Issue by cong235** [Cryptorubic/rubic-app#550]
Build at: 2021-07-14T07:19:52.308Z - Hash: 1d91986762e823aa6c9f - Time: 104506ms

Error: ./node_modules/@maticnetwork/meta/network/index.js
Module not found: Error: Can't resolve './networks' in '/Users/xxxx/Documents/rubic-app/node_modules/@maticnetwork/meta/network'

When I try to run by: npm start.
I meet this problem

**Comment by siandreev** [comment]
@cong235 the installation configuration has been updated. Please delete the `node_modules` folder and try again. I recommend using node 16.6 and npm 7.19
